baseURL = "https://blog.draftsofcode.dev/"
languageCode = "en-us"
theme = "mainroad"
paginate = "10"

[Params]
    copyright = "Rodney J. Woodruff. All rights reserved."
    opengraph = true
    schema = true
    twitter_cards = true
    readmore = true
    authorbox = true
    toc = true
    post_meta = ["author", "date", "categories"]
    dateformat = "Mon, Jan 2, 2006"
    googleAnalyticsID = "G-Z2SG8RMRBE"

[Author]
    name = "Rodney J. Woodruff"
    bio = "Rodney J. Woodruff has spent his entire life in science and engineering. draftsOfCode is the blog where Rodney will share his design and build process for building his hobby projects. He reserves the right to stop working on a project at any time. :)"
    avatar = "img/me_in_red.jpg"

[Params.logo]
    image = "img/draftsOfCode_logo_nobackground_narrow.svg"
    subtitle = "A million ideas worked on one at a time!"

[Params.sidebar]
    home = "right"
    list = "right"
    single = true
    widgets = ["search", "recent", "categories", "taglist", "social", "languages", "newsletter"]

[Params.widgets]
    recent_num = 5

[Params.widgets.social]
    twitter = "draftsOfCode"
    instagram = "draftsOfCode"
    github = "draftsOfCode"
    email = "draftsOfCode@draftsofcode.dev"

[[Params.widgets.social.custom]]
    title = "My Home Page"
    url = "https://blog.rodneyjwoodruff.com"